americanexpress/one-app-cli

- packages/one-app-bundler/webpack/loaders/ssr-css-loader/index-style-loader.js
This ensures that win32 slashes are handled.
Fixes #10
Steps to verify:
1. Cloned repo locally on a Windows machine (checked out this branch)
2. Ran `npm install` 
3. `cd` install `one-app-bundler`
4. Ran `npm pack`
5. npm installed the tgz file
6. Ran `npm build`
Below you can see the result
> fix(path): ensure path to css-base.js is JSON.stringified

- packages/one-app-bundler/bin/postProcessOneAppBundle.js
This chunk metadata is used by One App, instead of having One App read directly from the webpack-stats-* files which are huge and cause memory issues we now only store the relevant details in the `.build-meta.json` file. This also allows us to stop publishing these large webpack-stats-* files with our One App docker images.
> feat(one-app-bundler): add chunk meta to one app build.meta file

- CHANGELOG.md
- lerna.json
- packages/eslint-plugin-one-app/CHANGELOG.md
- packages/eslint-plugin-one-app/package-lock.json
- packages/eslint-plugin-one-app/package.json
- packages/generator-one-app-module/CHANGELOG.md
- packages/generator-one-app-module/package-lock.json
- packages/generator-one-app-module/package.json
- packages/one-app-bundler/CHANGELOG.md
- packages/one-app-bundler/package-lock.json
- packages/one-app-bundler/package.json
- packages/one-app-locale-bundler/CHANGELOG.md
- packages/one-app-locale-bundler/package-lock.json
- packages/one-app-locale-bundler/package.json
used `npm run lerna:version` to generate a changelog and iterate the version in all repos within one-app-cli. This is being done in order to tag and, once merged w/ master, publish all repos to npm.
> update one-app-cli to v6.1.0

- packages/generator-one-app-module/package.json
necessary in order to publish `generator-one-app-module` to npm registry.
> fix(generator): add public access to publishConfig

- packages/generator-one-app-module/README.md
old npx command was faulty. The correct command (for our scoped library) is npx -p yo -p @americanexpress/generator-one-app-module -- yo @americanexpress/one-app-module
> docs(readme): update npx generator command

- package.json
- packages/generator-one-app-module/generators/app/templates/base-module/__tests__/.eslintrc.json
- packages/generator-one-app-module/generators/app/templates/base-module/__tests__/components/ModuleContainer.spec.jsx
- packages/generator-one-app-module/generators/app/templates/base-module/__tests__/enzyme.config.js
- packages/generator-one-app-module/generators/app/templates/base-module/__tests__/index.spec.js
- packages/generator-one-app-module/generators/app/templates/base-module/enzyme.config.js
- packages/generator-one-app-module/generators/app/templates/base-module/package.json
- packages/generator-one-app-module/generators/app/templates/base-module/src/appConfig.js
- packages/generator-one-app-module/generators/app/templates/base-module/src/components/ModuleContainer.jsx
- packages/generator-one-app-module/generators/app/templates/base-module/src/csp.js
adds rudimentary tests for a generated module.
a few considerations I've gone back and forth on related to the generator and this PR:
1) decided against creating a prompt for the user to choose between creating a `root module` and `child module`. The only difference between the two is the inclusion of `csp` in the appConfig, which the user will become aware of while reading the recipe docs. Providing the two separate options I think would cause confusion (especially at initial quick start) and force the generator to provide two separate scaffolds that only differ in a few lines of code.
2) unit tests have stayed very basic. I initially wrote tests that used `jest-json-schema` to type-check every property that could be added to appConfig, but since all properties but csp are optional, I …
> test(jest): add __tests__ directory for base-module

- packages/one-app-bundler/README.md
Making it more clear as I noticed that my first instinct was to add the external config in the child module without installing it first.
> docs(one-app-bundler): clarify global providers config

- CHANGELOG.md
- lerna.json
- packages/eslint-plugin-one-app/CHANGELOG.md
- packages/eslint-plugin-one-app/package-lock.json
- packages/eslint-plugin-one-app/package.json
- packages/generator-one-app-module/CHANGELOG.md
- packages/generator-one-app-module/package-lock.json
- packages/generator-one-app-module/package.json
- packages/one-app-bundler/CHANGELOG.md
- packages/one-app-bundler/package-lock.json
- packages/one-app-bundler/package.json
- Release `webpackClientConfigPath` update
- MUST Squash and Merge this as `chore(release): 6.2.0` to properly release this.
> chore(release): 6.2.0

- packages/one-app-bundler/__tests__/webpack/app/webpack.client.spec.js
- packages/one-app-bundler/webpack/app/webpack.client.js
[isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch/issues) has not been updated in almost 5 years. switching [cross-fetch](https://github.com/lquixada/cross-fetch) as it is actively maintained. Both fulfil the same role.
> feat(one-app-bundler): use cross-fetch instead of isomorphic-fetch

- CHANGELOG.md
- lerna.json
- packages/eslint-plugin-one-app/CHANGELOG.md
- packages/eslint-plugin-one-app/package-lock.json
- packages/eslint-plugin-one-app/package.json
- packages/generator-one-app-module/CHANGELOG.md
- packages/generator-one-app-module/package-lock.json
- packages/generator-one-app-module/package.json
- packages/one-app-bundler/CHANGELOG.md
- packages/one-app-bundler/package-lock.json
- packages/one-app-bundler/package.json
- packages/one-app-runner/CHANGELOG.md
- packages/one-app-runner/package-lock.json
- packages/one-app-runner/package.json
Reverts americanexpress/one-app-cli#62
Need to revert this because
1. Since `lerna version` pushes tags, it doesn't like forks
2. Our commit message check expects a specific message and I forgot that.
> Revert "v6.5.0"

- packages/generator-one-app-module/generators/app/templates/base-child-module/package.json
- packages/generator-one-app-module/generators/app/templates/intl-child-module/__tests__/components/ModuleContainer.spec.jsx
- packages/generator-one-app-module/generators/app/templates/intl-child-module/src/components/ModuleContainer.jsx
- packages/generator-one-app-module/generators/app/templates/intl-root-module/__tests__/components/ModuleContainer.spec.jsx
- packages/generator-one-app-module/generators/app/templates/intl-root-module/src/components/ModuleContainer.jsx
Removed `holocronModule` HOC from the following generators
- `int-child-module`
- `intl-root-module`
updated `base-child-module` holocron dependency to ^1.1.0
> fix(generator): remove deprecated holocron api

- packages/one-app-bundler/package-lock.json
- packages/one-app-bundler/package.json
Currently we use `url-loader` for images https://github.com/americanexpress/one-app-cli/blob/master/packages/one-app-bundler/webpack/webpack.common.js#L64. However, `url-loader` is not a dependency of the bundler. This causes issues when you try to do `import image from './image.png';` and then use it like `<img src={image} />`.
> fix(url-loader): add missing dep of url-loader

- lerna.json
This enables https://github.com/lerna/lerna/blob/master/README.md#independent-mode. We are currently running into an issue where every package is being bumped when only 1 package has changes. This is not good especially if one of our packages needs to make a major version bump and the others do not.
> chore(lerna): setup independent versioning for lerna

- packages/one-app-bundler/README.md
- packages/one-app-bundler/__tests__/webpack/module/webpack.client.spec.js
- packages/one-app-bundler/webpack/module/webpack.client.js
Added missing `maxEntrypointSize` to the webpack client configuration.
Changed the default value for both `maxAssetSize` and `maxEntrypointSize` to 250e3 instead of 200e3.
We previously discussed about increasing the default performance budget, and seems like the 250e3 is a sane default also used by `webpack` in their official docs 
https://webpack.js.org/configuration/performance/#performancemaxentrypointsize
> fix(one-app-bundler): maxEntrypointSize and increase default to 250e3

- packages/one-app-bundler/__tests__/utils/__snapshots__/extendWebpackConfig.spec.js.snap
- packages/one-app-bundler/__tests__/utils/extendWebpackConfig.spec.js
- packages/one-app-bundler/utils/extendWebpackConfig.js
There was an issue where if a library like iguazu was listed ahead of a library
like iguazu-rpc, iguazu was getting bundled instead of iguazu-rpc.
> fix(bundler): fix an issue with requiredExternals

- packages/one-app-runner/README.md
- packages/one-app-runner/__tests__/bin/__snapshots__/one-app-runner.spec.js.snap
- packages/one-app-runner/__tests__/src/__snapshots__/startApp.spec.js.snap
- packages/one-app-runner/__tests__/src/startApp.spec.js
- packages/one-app-runner/bin/create-runner-env.js
- packages/one-app-runner/bin/one-app-runner-test.js
- packages/one-app-runner/bin/one-app-runner.js
- packages/one-app-runner/package-lock.json
- packages/one-app-runner/package.json
- packages/one-app-runner/src/startApp.js
1. Accepts a new flag: createDockerNetwork
2. Creates a new command: `one-app-runner-test` that starts one-app in the background, using the host and connected to a network ready to run tests
3. Adds a new command: `create-runner-env` that creates a random network name and checks for available ports
> feat(one-app-runner): create network and env file

- packages/generator-one-app-module/__tests__/app.js
- packages/generator-one-app-module/generators/app/index.js
- packages/generator-one-app-module/generators/app/templates/base-child-module/package.json
Add `npm start` to use `one-app-runner` pointing at the latest one-app-dev docker image.
Also downgraded the parrot-middleware version due to a current issue with commonjs export
> feat(generator): add one-app-runner script

- packages/generator-one-app-module/generators/app/templates/base-child-module/gitignore
A `.build-cache` directory is generated by One App. This PR adds it to the `.gitignore` for the yeoman generator.
> feat(generator): adds .build-cache to gitignore

- packages/one-app-bundler/__tests__/webpack/loaders/__snapshots__/common.spec.js.snap
- packages/one-app-bundler/webpack/app/webpack.client.js
- packages/one-app-bundler/webpack/loaders/common.js
[`css-loader`](https://github.com/webpack-contrib/css-loader) should have the option [`importLoaders`](https://github.com/webpack-contrib/css-loader#importloaders) set if used with other loaders per rule. Relates to #79
> fix(css-loader): add import loaders count

- packages/one-app-runner/docs/recipes/README.md
- packages/one-app-runner/docs/recipes/Using-With-Windows.md
Just a very basic how to get docker on windows up and running. After installing docker for Windows it is no different than running on Linux or macOS (in my experience)
> docs(recipes): add one-app-runner recipe

- packages/generator-one-app-module/__tests__/app.js
- packages/generator-one-app-module/generators/app/index.js
- packages/one-app-bundler/__tests__/webpack/module/webpack.server.spec.js
Fixed correct syntax for `providedExternals` to be an array of strings instead of a string.
Fixed issue with side effect in tests for one-app-bundler
> fix(generator): react-intl in externals

- packages/eslint-plugin-one-app/CHANGELOG.md
- packages/eslint-plugin-one-app/package-lock.json
- packages/eslint-plugin-one-app/package.json
- packages/generator-one-app-module/CHANGELOG.md
- packages/generator-one-app-module/package-lock.json
- packages/generator-one-app-module/package.json
- packages/one-app-bundler/CHANGELOG.md
- packages/one-app-bundler/package-lock.json
- packages/one-app-bundler/package.json
- packages/one-app-locale-bundler/CHANGELOG.md
- packages/one-app-locale-bundler/package-lock.json
- packages/one-app-locale-bundler/package.json
- packages/one-app-runner/CHANGELOG.md
- packages/one-app-runner/package-lock.json
- packages/one-app-runner/package.json
For some reason when running `npm run learna:version` I got the following:
```
lerna ERR! husky > commit-msg (node v12.18.3)
lerna ERR! ⧗   input: Publish
lerna ERR! 
lerna ERR!  - @americanexpress/eslint-plugin-one-app@6.9.0
lerna ERR!  - @americanexpress/generator-one-app-module@6.9.0
lerna ERR!  - @americanexpress/one-app-bundler@6.9.0
lerna ERR!  - @americanexpress/one-app-locale-bundler@6.2.0
lerna ERR!  - @americanexpress/one-app-runner@6.9.0
lerna ERR! ✖   subject may not be empty [subject-empty]
lerna ERR! ✖   type may not be empty [type-empty]
lerna ERR! 
lerna ERR! ✖   found 2 problems, 0 warnings
lerna ERR! ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
lerna ERR! 
lerna ERR! husky > commit-msg hook failed (add --no-verify to bypass) …
```
> chore(release): 6.9.0

- lerna.json
This would add a default message when running `npm run lerna:version` to prevent the precommit messages from failing
https://github.com/lerna/lerna/tree/master/commands/version#--message-msg
> chore(release): add message when running lerna:version locally

- packages/one-app-bundler/webpack/app/webpack.client.js
- packages/one-app-bundler/webpack/module/webpack.client.js
- packages/one-app-bundler/webpack/module/webpack.server.js
Tested with the following 
```jsx
export const MyRoot = () => (
<nav>
<ul>
<li>
<a>Test</a>
</li>
</ul>
</nav>
);
```
```sass
nav
ul
margin: 0
padding: 0
list-style: none
li
display: inline-block
a
display: block
padding: 6px 12px
text-decoration: none
```
> feat(sass): allow the use of sass files

- packages/one-app-bundler/__tests__/webpack/app/webpack.client.spec.js
- packages/one-app-bundler/webpack/app/webpack.client.js
Add `cross-fetch/polyfill` and `abort-controller/polyfill` to the legacy bundle of the app.
Tested using npm pack and installing this bundler version to one app, making a client side fetch call no longer results in errors from the `app.js` bundle when running on IE11
> fix(fetch): cross-fetch and abort-controller polyfills

- packages/one-app-runner/README.md
- packages/one-app-runner/__tests__/bin/__snapshots__/one-app-runner.spec.js.snap
- packages/one-app-runner/__tests__/bin/one-app-runner.spec.js
- packages/one-app-runner/__tests__/src/__snapshots__/startApp.spec.js.snap
- packages/one-app-runner/__tests__/src/startApp.spec.js
- packages/one-app-runner/bin/one-app-runner.js
- packages/one-app-runner/src/startApp.js
New feature:
Pass the --offline option to one-app-runner to bypass `docker pull` and work offline when the image has been downloaded already and you are offline or not able to connect to the Docker registry
fixes https://github.com/americanexpress/one-app-cli/issues/44
> feat(runner): add offline flag

- package-lock.json
- package.json
- packages/one-app-bundler/__tests__/utils/__snapshots__/extendWebpackConfig.spec.js.snap
- packages/one-app-bundler/__tests__/utils/extendWebpackConfig.spec.js
- packages/one-app-bundler/utils/extendWebpackConfig.js
- packages/one-app-bundler/webpack/createResolver.js
[enhance-resolve](https://github.com/webpack/enhanced-resolve) `resolveToContext` resolves to a directory not a file, however if we don't add a trailing slash to indicate the end of the absolute path, the [test](https://webpack.js.org/configuration/module/#condition) matcher from webpack module incorrectly resolves paths that start with the same name and are separated by a hyphen i.e. `iguazu` will be resolved instead of `iguazu-rpc` if the trailing slash is not present. see https://github.com/americanexpress/one-app-cli/pull/81
This PR adds the correct trailing slash depending on the platform i.e. windows/darwin to the `createResolver.js` when `resolveToContext` is true
> fix(bundler): add trailing slash to externals resolver

- packages/one-app-bundler/__tests__/utils/getConfigOptions.spec.js
- packages/one-app-bundler/__tests__/webpack/loaders/meta-data-loader.spec.js
- packages/one-app-bundler/__tests__/webpack/loaders/validate-externals-loader.spec.js
- packages/one-app-bundler/__tests__/webpack/module/webpack.server.spec.js
- packages/one-app-bundler/bin/postProcessOneAppBundle.js
- packages/one-app-bundler/utils/getConfigOptions.js
- packages/one-app-bundler/webpack/loaders/meta-data-loader.js
- packages/one-app-bundler/webpack/loaders/validate-required-externals-loader.js
- packages/one-app-bundler/webpack/module/webpack.server.js
Our tests didn't catch `pkg` not being returned by `read-pkg-up` due to mocking the return values in the tests to use `pkg`.
> fix(readPkgUp): fix use packageJson from readPkgUp.sync instead of pkg

- packages/eslint-plugin-one-app/CHANGELOG.md
- packages/eslint-plugin-one-app/package.json
- packages/generator-one-app-module/CHANGELOG.md
- packages/generator-one-app-module/package.json
- packages/one-app-bundler/CHANGELOG.md
- packages/one-app-bundler/package.json
- packages/one-app-locale-bundler/CHANGELOG.md
- packages/one-app-locale-bundler/package.json
- packages/one-app-runner/CHANGELOG.md
- packages/one-app-runner/package.json
- @americanexpress/eslint-plugin-one-app@6.12.0
- @americanexpress/generator-one-app-module@6.12.0
- @americanexpress/one-app-bundler@6.12.0
- @americanexpress/one-app-locale-bundler@6.5.0
- @americanexpress/one-app-runner@6.12.0
> chore(release): publish 6.12.0

- commitlint.config.js
Disable the body length rule. For reference https://commitlint.js.org/#/reference-rules
> chore(commit): disable body length

- .github/workflows/labeler.yml
This actions now supports forks safely https://github.com/actions/labeler/issues/12#issuecomment-670967607
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
> chore(actions): fix for labeler actions

- packages/one-app-bundler/__tests__/utils/extendWebpackConfig.spec.js
- packages/one-app-bundler/utils/extendWebpackConfig.js
This pull request adds a feature as well as solves a bug with the webpack merge. When a merge occurs on the `plugins` webpack configuration key, duplicate plugins are appended to the array instead of using the override version. Further, with the use of `merge.smartStrategy`, module rules can be properly appended into their appropriate rule given that the custom rule matches an existing rule.
```javascript
// original webpack configuration
{
plugins: [new OneAppAwesomePlugin()],
};
// user webpack configuration
{
plugins: [new OneAppAwesomePlugin({ withSomeAwesomeAdditions: true })],
}
// the resulting merge has two duplicates
// result:
{
plugins: [new OneAppAwesomePlugin(), new OneAppAwesomePlugin({ withSomeAwesomeAdditions: true })],
}
```
```javascript
// original webpack configuration …
```
> feat(extendWebpackConfig): added smartStrategy

- packages/holocron-dev-server/__tests__/src/utils/config.spec.js
- packages/holocron-dev-server/src/utils/config.js
if a locally served module did not have a `one-amex` key this would throw an error.
> fix(getPackageJsonConfig): module does not require one-amex key

- packages/holocron-dev-server/__tests__/src/utils/statics.spec.js
- packages/holocron-dev-server/src/utils/statics.js
arguments passed to `execSync`  were in incorrect format. should be `child_process.execSync(command[, options])` https://nodejs.org/docs/latest-v12.x/api/child_process.html#child_process_child_process_execsync_command_options
> fix(dev-server): load App Statics from docker img

- .github/dependabot.yml
- .github/workflows/automated-pr.yml
- .github/workflows/automerge-dependabot.yml
Automerge of dependabot PRs to branch dependabot-changes
Adding automated PR that is raised every Monday with changes
Automate tasks and reduce the number of PRs we have to review and still ensure the project is upto date
- auto merging  minor and patches after they pass tests e.g https://github.com/nellyk/task-list-pr-checker/pull/59 this is workflow https://github.com/nellyk/task-list-pr-checker/blob/main/.github/workflows/automerge.yml
- Automated PR is then raised with all the changes  https://github.com/nellyk/task-list-pr-checker/pull/63 and https://github.com/nellyk/redux-exercise-notes/pull/30
> Add automerge feature for dependabot PRs

- .github/workflows/publish.yml
- CONTRIBUTING.md
- package.json
After much trial an error I have decided to revert to the method of locally versioning. This has an increased change that the tags are left pointing to commits that do not end up on the main branch. The reason for this is due to the way github enforces status checks on branch protection. I have been unable to figure out how status checks can rerun as part of `lerna version`. 
https://github.com/americanexpress/one-app-cli/runs/5278800963?check_suite_focus=true
It possible that the following steps  in an action could get around this restriction but i am running out of time to verify
* run `lerna version --no-push`
* open a pr from a new branch
* wait for status checks to succeed on the branch
* on success push to main
* finally run `lerna publish`
> chore(publish): revert to manual version step

- .github/labeler.yml
- packages/one-app-bundler/__tests__/webpack/module/webpack.client.spec.js
- packages/one-app-bundler/package.json
- packages/one-app-bundler/webpack/module/webpack.client.js
- yarn.lock
Library name is changed in `webpack.client.js` to fix issue of web-pack filename clashing during lazy loading.
To fix lazy loading issue caused by web-pack filename clash.
- [ X] Bug fix (non-breaking change which fixes an issue)
> fix(lazy-loading): fixed webpack filename clashing issue

- .github/workflows/health-check.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml
- packages/generator-one-app-module/__tests__/app.js
- packages/generator-one-app-module/generators/app/index.js
- packages/generator-one-app-module/package.json
- packages/one-app-bundler/__tests__/webpack/webpack.common.spec.js
- packages/one-app-bundler/webpack/webpack.common.js
- yarn.lock
Addresses: https://github.com/webpack/webpack/issues/14532
Current hashing method is unsupported by Node 17+
Installed and built in one-app using Node 18
> fix(bundler): default hashing method doesnt work in node 18

- packages/eslint-plugin-one-app/CHANGELOG.md
- packages/eslint-plugin-one-app/package.json
- packages/generator-one-app-module/CHANGELOG.md
- packages/generator-one-app-module/package.json
- packages/holocron-dev-server/CHANGELOG.md
- packages/holocron-dev-server/package.json
- packages/one-app-bundler/CHANGELOG.md
- packages/one-app-bundler/package.json
- packages/one-app-locale-bundler/CHANGELOG.md
- packages/one-app-locale-bundler/package.json
- packages/one-app-runner/CHANGELOG.md
- packages/one-app-runner/package.json
- @americanexpress/eslint-plugin-one-app@6.13.0
- @americanexpress/generator-one-app-module@6.12.2
- @americanexpress/holocron-dev-server@0.1.4
- @americanexpress/one-app-bundler@6.15.1
- @americanexpress/one-app-locale-bundler@6.5.3
- @americanexpress/one-app-runner@6.14.0
`yarn lerna:version`
Changes:
- @americanexpress/eslint-plugin-one-app: 6.12.0 => 6.13.0
- @americanexpress/generator-one-app-module: 6.12.1 => 6.12.2
- @americanexpress/holocron-dev-server: 0.1.3 => 0.1.4
- @americanexpress/one-app-bundler: 6.15.0 => 6.15.1
- @americanexpress/one-app-locale-bundler: 6.5.2 => 6.5.3
- @americanexpress/one-app-runner: 6.13.0 => 6.14.0
> chore(release): publish packages

- packages/one-app-bundler/__tests__/webpack/app/webpack.client.spec.js
- packages/one-app-bundler/webpack/app/webpack.client.js
This is needed for Node 17 and greater, otherwise the --openssl-legacy-provider flag is required.
Node.js v17 included OpenSSL 3.0 support, which removed support for certain crypto algorithms like `md4`. `md4` is the default for Webpack 4. This change introduces a monkey patch to use sha256 instead. 
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V17.md#openssl-30
> fix(hash): use OpenSSL supported hash for webpack

- packages/one-app-dev-bundler/__tests__/esbuild/plugins/one-app-index-loader.spec.js
- packages/one-app-dev-bundler/esbuild/plugins/one-app-index-loader.js
The index loader was using the full path as the regex matcher for the esbuild filter. 
On windows machines, the regex was failing because of the path separator on Windows (`\` backslash).
This makes the regex more generic to support both windows and mac.
dev bundler was broken on windows
> fix(indexloader): regex was failing on windows machines

- packages/one-app-dev-bundler/__tests__/esbuild/plugins/styles-loader.spec.js
- packages/one-app-dev-bundler/esbuild/plugins/styles-loader.js
Add named CSS module exports.
From https://github.com/css-modules/css-modules#readme both default and named exports should be usable:
> When importing the **CSS Module** from a JS Module, it exports an object with all mappings from local names to global names.
> 
> ``` js
> import styles from "./style.css";
> // import { className } from "./style.css";
> 
> element.innerHTML = '<div class="' + styles.className + '">';
> ```
Currently the dev bundler only provides the default export.
Additional specification added ("Esbuild plugin stylesLoader lifecycle Hooks PRODUCTION environment should transform inputs to named outputs for purged css, browser").
> fix(devBundler): support named exports from style files

- packages/one-app-dev-bundler/__tests__/esbuild/plugins/font-loader.spec.js
- packages/one-app-dev-bundler/__tests__/esbuild/plugins/image-loader.spec.js
- packages/one-app-dev-bundler/esbuild/plugins/externals-loader.js
- packages/one-app-dev-bundler/esbuild/plugins/font-loader.js
- packages/one-app-dev-bundler/esbuild/plugins/image-loader.js
- match a period, rather than wildcard: `.` to `\.`
- case insensitive on file extensions: `i` flag 
- `image.JPG` is an older way of naming files, kind of like HTML tags, but not invalid, may also save a dev some frustration when using both sensitive and insensitive filesystems (Linux, macOS)
- simplify suffix variations: e.g. `e` is commonly left out in `jpeg` (convention stemming from a previous Windows? 5+3 rule) so `jpe?g` is a compact way to specify both (note that we're already using `s?css` to match `css` and `scss`)
From #507 I figured a walkthrough of other RegExp's might be useful, just in case. I didn't find any other slash issues, so this PR might just be #nitpicky 😅  
~~unchanged for brevity, but would it be preferred to add scenarios similar to #507?~~
Added sample paths, …
> fix(one-app-dev-bundler): match a period, rather than wildcard

- packages/one-app-locale-bundler/__tests__/index.spec.js
- packages/one-app-locale-bundler/index.js
Prints a console log message instead of throwing an error if an error is encountered in watch mode.  If not in watch mode, existing behavior of exiting immediately is unchanged.
Fixes #510 
Having the watch mode ever exit on errors leads to a worse developer experience, since any additional code changes will not be built.
Tested with unit tests and by making the change in local version of locale-bundler.
This shows a locale file having a syntax error introduced and then removed, and being rebuilt after it was fixed:
```
$ npm run watch:build
> project@1.0.0 watch:build
> bundle-module --dev --watch
Running dev bundler
Generated language packs for en-US
Watching...
Error generating language packs: SyntaxError: Unexpected token 
in JSON at position 5398
Generated language packs for en-US …
```
> fix(locale-bundler): do not exit on errors during watch

- packages/one-app-dev-bundler/__tests__/esbuild/plugins/bundle-asset-size-limiter.spec.js
- packages/one-app-dev-bundler/__tests__/esbuild/plugins/cjs-compatibility-hotpatch.spec.js
- packages/one-app-dev-bundler/__tests__/esbuild/plugins/generate-integrity-manifest.spec.js
- packages/one-app-dev-bundler/__tests__/esbuild/plugins/restrict-runtime-symbols.spec.js
- packages/one-app-dev-bundler/__tests__/esbuild/plugins/server-styles-dispatcher.spec.js
- packages/one-app-dev-bundler/esbuild/plugins/bundle-asset-size-limiter.js
- packages/one-app-dev-bundler/esbuild/plugins/cjs-compatibility-hotpatch.js
- packages/one-app-dev-bundler/esbuild/plugins/generate-integrity-manifest.js
- packages/one-app-dev-bundler/esbuild/plugins/restrict-runtime-symbols.js
- packages/one-app-dev-bundler/esbuild/plugins/server-styles-dispatcher.js
Do not run the `onEnd` plugins when the results metadata is not defined.
Fixes #512 
When the build fails due to a syntax error or similar, the `onEnd` plugins are called with a results object that does not have a `metadata` key.  Most of the plugins have reference to `result.metafile.outputs` so they themselves throw an error, which thoroughly obscures the original syntax error.
Unit tests plus ran changes locally.  Output shows only the two relevant failures, rather than pages of stack traces.
```
* $ npm run watch:build
> package@1.0.0 watch:build
> bundle-module --dev --watch
Running dev bundler
Generated language packs for en-US
Watching...
✘ [ERROR] Could not resolve "./Dynamic Table"
src/components/history/History.jsx:9:39:
9 │ import DynamicTable from './Dynamic Table';
╵ …
```
> fix(dev-bundler): skip plugins when no results metadata

- packages/one-app-dev-bundler/package.json
- yarn.lock
Upgrade to cssnano@5. Fixes #517 
⚠️ cssnano@6 is the current version but it drops node 12 support which would likely be considered a breaking change.
It's a little confusing since the change notes for v5 say to use the syntax this project is already using.
https://github.com/cssnano/cssnano/releases/tag/cssnano%405.0.0
Also, the code seems to only use cssnano when the dev bundler is run in production mode which I don't believe is ever the case, so maybe this was for future use?
Upgrade to current major to resolve some security vulnerabilities in sub-dependencies.
Verified unit tests passed.
> fix(devBundler): upgrade to cssnano@5

- packages/one-app-bundler/package.json
- yarn.lock
Closes #496
html-webpack-plugin@3 brings in loader-utils@0.2.17 which is very old and has unpatched vulnerabilities.
html-webpack-plugin plugin is not used directly but is a peer dep of webpack-subresource-integrity.
https://github.com/waysact/webpack-subresource-integrity/blob/1.x/package.json#LL79C1-L79C1
This PR updates the dependency to the latest value that is supported by that package.
Two notes:
1) I don't think the bundler even uses the html-webpack-plugin support so I tried uninstalling it entirely but that causes the tests to fail.  Suspect this is due to node version upgrades since they do wrap the `require` in a try/catch.
2) I'm not sure that the bundler even uses webpack-subresource-integrity, but not sure enough to remove it.
* Should be a safe upgrade since the version is …
> chore(deps): upgrade peer dep html-webpack-plugin

- packages/one-app-dev-bundler/__tests__/esbuild/plugins/prevent-prod-builds-for-now.spec.js
- packages/one-app-dev-bundler/esbuild/plugins/prevent-prod-builds-for-now.js
Closes #527 
Changes the message when NODE_ENV != 'development' to be more descriptive, and not to suggest reporting an issue.
```
_____ _______ ____  _____  
/ ____|__   __/ __ \|  __ \ 
| (___    | | | |  | | |__) |
\___ \   | | | |  | |  ___/ 
____) |  | | | |__| | |     
|_____/   |_|  \____/|_|     
This bundler is only enabled for local development.
NODE_ENV variable is set to 'production' but must be set to 'development'.
```
The other case where it is not set at all:
```
NODE_ENV variable is set to 'undefined' but must be set to 'development'.
```
Old message:
```
This bundler is only enabled for local development. If you see this message please raise an issue
```
Updated unit tests.
Ran `yarn pack` and installed in a module and validated updated message was shown.
> fix(dev-bundler): improve error when NODE_ENV not development

- packages/one-app-runner/bin/one-app-runner-test.js
Closes #524 
The console messaging did not use proper One App product names and was inaccurate in the case where the server did not startup.
New output:
```
Waiting for One App to start on port 51954
One App failed to start within 200000ms. Please check the one-app-test.log for more information.
```
Ran `yarn pack` and then installed the resulting package to a module.  Changed the module map to be incorrect and ran `one-app-runner-test` and produced expected output.
> fix(one-app-runner-test): improve console messaging

- CONTRIBUTING.md
- RELEASE.md
create a new RELEASE doc to make it clear where the release instructions are.
Added a new step to the release process, which is to fetch tags before starting the release.
Not doing so has caused issues in the past.
> chore(docs): add release doc

- packages/one-app-dev-bundler/__tests__/esbuild/plugins/styles-loader.spec.js
- packages/one-app-dev-bundler/esbuild/plugins/styles-loader.js
Use the documented import API.
The "default" export was accidentally removed in sass@1.63.0 through 1.63.3. It will be removed in 2.x per https://github.com/sass/dart-sass/issues/2008. It will likely be added back in 1.63.4 via https://github.com/sass/dart-sass/pull/2009 but we can use the documented API now.
Jest is not set up to use the ESM import, so the unit tests do not catch the issue. While Jest is being updated in another PR, this has been tested on my machine with a newly generated module using sass@1.63.3.
> fix(one-app-dev-bundler): avoid default export of sass

- packages/one-app-bundler/README.md
Soften up the language around disabling purgecss.
Unless I'm misunderstanding, "the effect of disabling will have a negative impact on performance" does not seem accurate to me.  If a module uses minimal CSS, and some of it is being incorrectly stripped out by purgecss, disabling purgecss seems like a straightforward way to fix the issue, and scary language doesn't help here.
> docs(readme): soften language around disabling purgecss

- packages/one-app-dev-bundler/__tests__/esbuild/plugins/externals-loader.spec.js
- packages/one-app-dev-bundler/esbuild/plugins/externals-loader.js
On one-app v5, modules will fail to load because `Holocron.getExternal` does not exist.
We also do this check in the prod-bundler, so better to keep consistency with the prod bundler.
This was causing modules to fail to load when build with the dev-bundler locally.
modified the bundler of a module to include these changes, and it loaded without issue
> fix(devBundler): check for Holocron.getExternal

- packages/one-app-dev-bundler/esbuild/plugins/styles-loader.js
For some reason this [change](https://github.com/americanexpress/one-app-cli/commit/0d9b5b422a9e18cc6391fa119abe41b7d384c154) was reverted, possibly due to a bad rebase. 
See https://github.com/sass/dart-sass/issues/2008
> fix(dev-bundler): styles loader

- .github/workflows/publish.yml
replace
```shell
echo "::set-output name={name}::{value}"
```
with
```shell
echo "{name}={value}" >> $GITHUB_OUTPUT
```
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
these are now showing as warnings in the runs, e.g. https://github.com/americanexpress/one-app/actions/runs/6344142425
https://github.com/americanexpress/one-app/pull/1141
> chore(workflows): use GITHUB_OUTPUT instead of ::set-output

- packages/one-app-runner/__tests__/src/startApp.spec.js
- packages/one-app-runner/src/startApp.js
When users configure `createSsrFetch` with [createBrowserLikeFetch](https://github.com/americanexpress/fetch-enhancers/tree/main), and run their module with the one-app-runner, it would fail with an error `q.headers.raw` is not a function.
This only happened on one-app version 5.21.0 and greater, as that was the release that included the Node 18 uplift.
The runner wasn't running one-app with the `--no-experimental-fetch` flag, so the default node fetch implementation was used, and it apparently doesn't have `headers.raw` in its response.
This change disables experimental fetch in the one-app-runner to match what the production server is started with.
Caused issues locally for developers
Ran with a module that had this issue. packed and installed this branch and confirm it worked.
Also …
> fix: disable native fetch in node

- packages/one-app-runner/__tests__/src/startApp.spec.js
- packages/one-app-runner/src/startApp.js
Set `update-notifier` to false before running any `npm` commands.  This avoids printing a notification that npm has an update available on every one-app start.
Fixes #588
I used the top-voted solution on this question:
https://stackoverflow.com/questions/46800717/eliminate-npm-update-available-message
The other options seemed either undocumented or needed to be used on the first `npm` command which is more complicated since the commands are dynamically geneated.
Ran `yarn pack` and then installed the `one-app-runner` package in my module.  Verified that npm update notification was no longer showing.
> fix(one-app-runner): suppress npm update notifications

- packages/one-app-bundler/__tests__/webpack/loaders/externals-loader.spec.js
- packages/one-app-bundler/webpack/loaders/externals-loader.js
- packages/one-app-bundler/webpack/loaders/provided-externals-loader.js
A Holocron Modules Pure ESM depenencies may not include `package.json` in the exports list. Currently the bundler will fail for external deps with `Error: Package subpath './package.json' is not defined by "exports"`. This resolves the issue by not using `require` to load the dependencies package.json
Improve support for externalizing pure ESM dependencies 
Test suite. local test with a module which externlized a dependency which is ESM only. Started with failure case and after change build was able to complte successfully
> fix(one-app-bundler): packages don't include package.json in exports

- packages/one-app-runner/__tests__/src/startApp.spec.js
- packages/one-app-runner/src/startApp.js
when an image provided to the one-app-runner is built with node 12, it would fail to start up.
This is because the flags `--no-experimental-fetch` and `--dns-result-order=ipv4first` are not valid for node 12.
This PR fixes #593 by only adding these flags for versions higher than 5.13.0 of one-app, which is the version that supports node 16.
This was tested against a module and verified the server starts.
> fix: runner failed to start with node 12 images

- packages/one-app-bundler/bin/postProcessOneAppBundle.js
- packages/one-app-bundler/bin/webpackCallback.js
- packages/one-app-dev-bundler/__tests__/esbuild/plugins/time-build.spec.js
- packages/one-app-dev-bundler/__tests__/utils/analyze-bundles.spec.js
- packages/one-app-dev-bundler/esbuild/plugins/time-build.js
- packages/one-app-dev-bundler/utils/analyze-bundles.js
This relocates all webpack and esbuild stat files under a `.build-stats` directory. 
Addressing https://github.com/americanexpress/one-app-cli/issues/592
See issue https://github.com/americanexpress/one-app-cli/issues/592
> fix(build-stats): esbuild and webpack stats under build-stats dir

- packages/one-app-bundler/__tests__/webpack/loaders/__snapshots__/common.spec.js.snap
- packages/one-app-bundler/webpack/loaders/common.js
Apply the purgecss loader to ts/tsx files as well as js/jsx files.
Fixes #600 where css imports are not being handled in typescript files.
It's a bit surprising that overly restricting purgecss would have this effect but it does seem to be the case.
Packed this and installed it on a repo that was having the bug and the styles were rendered properly.
> fix(webpack): include typescript files in purgecss loader

- packages/one-app-bundler/package.json
- yarn.lock
Update to the new major version of babel-preset-amex.
babel-preset-amex had a major version bump dropping support for EOL node versions 10/12/14.
(It's not 100% clear to me which node versions the bundler supports, but it's definitely not being tested with older versions.)
Bumping the version here will ensure that future updates get picked up.
Passed unit tests.
> chore(deps): upgrade to babel-preset-amex@4

- packages/one-app-runner/__tests__/src/startApp.spec.js
- packages/one-app-runner/src/startApp.js
single serve-module invocation
avoid repeated overhead with many modules for faster startup times to listening on the port
existing tests have inline snapshots of the command
> fix(one-app-runner): single serve-module invocation

- packages/one-app-bundler/__tests__/webpack/loaders/__snapshots__/common.spec.js.snap
- packages/one-app-bundler/__tests__/webpack/loaders/common.spec.js
- packages/one-app-bundler/package.json
- packages/one-app-bundler/webpack/loaders/common.js
- yarn.lock
Port of #613 to v6 of one-app-bundler.
See #613 for original motivation. 
Added unit tests to validate that css modules do not use `localName`. 
Additionally, validated the change locally by bundling a one app module, which uses a dependency that imports css modules, using the webpack-based bundler.
> fix(css-loader): do not use localName for css modules in node_modules

- packages/one-app-server-bundler/__tests__/bin/__snapshots__/serve-module.spec.js.snap
- packages/one-app-server-bundler/__tests__/bin/serve-module.spec.js
- packages/one-app-server-bundler/bin/serve-module.js
Always include a legacy bundle entry in module map
Serving modules without legacy bundles caused dev cdn to choke
- Updated unit
- Manually validated running serve-module
> fix(one-app-runner): include legacy bundle on serve-module even if it does not exist

- packages/one-app-runner/__tests__/src/startApp.spec.js
- packages/one-app-runner/src/startApp.js
Update to use the new `scripts/start.sh` entry command on v6.11.0 and newer
This is not required for the app to continue working, but is required for tracing and dotenv support. (I have not tested the dotenv support with this runner)
- Updated unit
- Used npm link to start up app versions 5.17.0, 5.23.0, 6.10.0 & 6.11.0-revert-node-20.0
> feat(one-app-runner): use new entry command in 6.11.0

- packages/one-app-server-bundler/__tests__/bin/serve-module.spec.js
- packages/one-app-server-bundler/bin/serve-module.js
Read and write the module map from/to disk O(1) rather than O(n) in serve-module.
Filesystem operations are slower than memory operations, so with #622 it'll be useful to reduce the total filesystem operations from `2*number of modules` to just `2`.
Should help reduce startup time with one-app-runner (albeit not as extreme as #622). 
existing tests pass 🙌 
added a test to verify the thrown exception message when no modules are provided
> fix(one-app-server-bundler): serve-module read and write the module map once

- packages/one-app-server-bundler/__tests__/webpack/app/__snapshots__/webpack.client.spec.js.snap
- packages/one-app-server-bundler/webpack/app/webpack.client.js
With the upgrade of `enhanced-resolve` from #619, we started to resolve CJS files.
We didn't transpile these files first, so newer syntax was throwing an error, example `zx ?? y`. 
This became obvious with the update to `react-redux` in the `next` branch of `one-app`, since the latest version of `react-redux` ships more modern builds.
Allow transpiling of cjs
Packed this change up and installed it in the failing branch in one-app, and confirmed it fixes the issue.
Also verified the regex still matches what we'd expect
> fix: transpile cjs files

- packages/one-app-dev-bundler/__tests__/esbuild/plugins/styles-loader.spec.js
- packages/one-app-dev-bundler/esbuild/utils/load-styles.js
> Note: this reverts an unintentional breaking change introduced with v7 of the one app bundler.
Updates `load-styles` to map css module class names using an "as-is" strategy, rather than a "camelCaseOnly" strategy in order to match the behavior of the webpack-based styles loader in `@americanexpress/one-app-bundler@6`. To be fully backwards-compatible with the webpack implementation, the exports needed to be changed to cjs-style exports.
In switching over to `load-styles` provided by the dev bundler with the release of `@americanexpress/one-app-bundler@7`, an unintentional breaking change was introduced to the way that css module classes were mapped and exported when loading the styles. The webpack-based styles loader exported classes "as-is", while the esbuild-based styles loader …
> fix(load-styles): export css module classes as-is
