- packages/eslint-plugin-one-app/package.json
- packages/one-app-bundler/package.json
- packages/one-app-locale-bundler/package.json
Per https://github.com/lerna/lerna/issues/178#issuecomment-261736824 adding publishConfig
> chore(package): add publishConfig to package.json

- lerna.json
This would enabled running of `lerna-version` on any other branch to allow for changelog generation and a new tag. 
Once that is done a pull request is submitted when merged will do a new release
> chore(lerna): allow versioning of tagged branches

- packages/eslint-plugin-one-app/package-lock.json
- packages/one-app-bundler/__tests__/webpack/ssr-css-loader/__snapshots__/index.spec.js.snap
- packages/one-app-bundler/__tests__/webpack/ssr-css-loader/index.spec.js
- packages/one-app-bundler/package-lock.json
- packages/one-app-bundler/package.json
- packages/one-app-bundler/webpack/loaders/ssr-css-loader/index.js
- Upgraded the internal css-loader replacements going from css-loader `3.3.0` to latest as of now, `^3.4.2`
CSS Loader in `3.3.0` inserted the following into the bundle:
```js
exports = module.exports = __webpack_require__(/*! ./node_modules/css-loader/dist/runtime/api.js */ "./node_modules/css-loader/dist/runtime/api.js")(false);
// Module
exports.push([module.i, "aside.my-root__OfflineWarning__offlineWarning___3qufd {\n  position: fixed;\n  width: 100%;\n  z-index: 100 !important;\n}\n\n.my-root__OfflineWarning__offlineFontFetcher___3IL4P {\n  position: absolute;\n}\n.my-root__OfflineWarning__offlineFontFetcher___3IL4P:before {\n  content: \" \";\n}", ""]);
// Exports
exports.locals = {
"offlineWarning": "my-root__OfflineWarning__offlineWarning___3qufd",
"offlineFontFetcher": …
```
> fix(css-loader): upgraded to latest css-loader api as of 3.4.2

- packages/one-app-bundler/__tests__/bin/__snapshots__/drop-module.spec.js.snap
- packages/one-app-bundler/__tests__/bin/drop-module.spec.js
- packages/one-app-bundler/bin/drop-module.js
it had not been updated to account for new module map shape
> Fix drop-module command

- README.md
adding one-app-runner to the root readme
> docs(readme): added one-app-runner to root readme

- packages/one-app-bundler/__tests__/webpack/app/__snapshots__/webpack.client.spec.js.snap
- packages/one-app-bundler/__tests__/webpack/loaders/__snapshots__/common.spec.js.snap
- packages/one-app-bundler/webpack/loaders/common.js
This adds a cache for babel, giving a significant build performance improvement
> feat(babel-loader): cache transpilation

- .travis.yml
- package-lock.json
- package.json
This adds Node 14 to the travis config
> chore(travis): add node 14 to travis config

- packages/one-app-bundler/package-lock.json
- packages/one-app-bundler/package.json
Prevent errors from larger resources added by `url-loader` when it falls back to `file-loader`.
https://github.com/webpack-contrib/url-loader#fallback
> fix(bundler/assets): fallback to file loader

- .github/dependabot.yml
According to this blog post by Dependabot https://dependabot.com/blog/lerna-support/ you just have to add the root directory.
> chore(dependabot): add dependabot config

- packages/generator-one-app-module/CHANGELOG.md
- packages/generator-one-app-module/package-lock.json
- packages/generator-one-app-module/package.json
> chore(generator): 6.8.0 release

- packages/eslint-plugin-one-app/CHANGELOG.md
- packages/eslint-plugin-one-app/package-lock.json
- packages/eslint-plugin-one-app/package.json
- packages/generator-one-app-module/CHANGELOG.md
- packages/generator-one-app-module/package-lock.json
- packages/generator-one-app-module/package.json
- packages/one-app-bundler/CHANGELOG.md
- packages/one-app-bundler/package-lock.json
- packages/one-app-bundler/package.json
- packages/one-app-runner/CHANGELOG.md
- packages/one-app-runner/package-lock.json
- packages/one-app-runner/package.json
bumping version number for release
> chore(release): one-app-generator-module 6.9.0

- packages/eslint-plugin-one-app/CHANGELOG.md
- packages/eslint-plugin-one-app/package-lock.json
- packages/eslint-plugin-one-app/package.json
- packages/generator-one-app-module/CHANGELOG.md
- packages/generator-one-app-module/package-lock.json
- packages/generator-one-app-module/package.json
- packages/one-app-bundler/CHANGELOG.md
- packages/one-app-bundler/package-lock.json
- packages/one-app-bundler/package.json
- packages/one-app-runner/CHANGELOG.md
- packages/one-app-runner/package-lock.json
- packages/one-app-runner/package.json
This reverts commit fe8725c808ed44ca52a60808ce83a60d2437cabb.
> chore(revert): revert 6.8.0 and 6.9.0 version bumps

- packages/generator-one-app-module/generators/app/index.js
This will initialize an empty git repository.
> chore(generator): initialize empty git repo

- packages/generator-one-app-module/__tests__/app.js
- packages/generator-one-app-module/package-lock.json
- packages/generator-one-app-module/package.json
This cleans up the folders that are generated during running the tests.
> test(generator): cleanup generated folders

- packages/one-app-bundler/__tests__/webpack/loaders/__snapshots__/common.spec.js.snap
- packages/one-app-bundler/__tests__/webpack/loaders/common.spec.js
- packages/one-app-bundler/webpack/loaders/common.js
- packages/one-app-bundler/webpack/loaders/ssr-css-loader/index.js
- packages/one-app-bundler/webpack/webpack.common.js
This has been tested locally with `semantic-ui-react` & `semantic-ui-css`, `react-bootstrap`, `bulma`, `material-ui`. Unfortunately I did have to disable `purgecss` for everything to work because it was removing styles that were being used by components.
Any `import styles from './RootStyles.scss';` includes this code
```css
.test {
background-color: blue;
}
```
```jsx
import React from 'react';
import {
Button, Container, Divider, Grid, Header, Image, Menu, Segment,
} from 'semantic-ui-react';
import 'semantic-ui-css/semantic.min.css';
import childRoutes from '../childRoutes';
import styles from './RootStyles.scss';
const SemanticUiRoot = () => (
<Container style={{ marginTop: '3em' }}>
<h1 className={styles.test}>TESTING</h1>
<Header as="h1">Theming Examples</Header>
<Header as="h2" …
```
> feat(bundler): allow the use of external library CSS

- CHANGELOG.md
- packages/eslint-plugin-one-app/CHANGELOG.md
- packages/eslint-plugin-one-app/package-lock.json
- packages/eslint-plugin-one-app/package.json
- packages/generator-one-app-module/CHANGELOG.md
- packages/generator-one-app-module/package-lock.json
- packages/generator-one-app-module/package.json
- packages/one-app-bundler/CHANGELOG.md
- packages/one-app-bundler/package-lock.json
- packages/one-app-bundler/package.json
- packages/one-app-locale-bundler/CHANGELOG.md
- packages/one-app-locale-bundler/package-lock.json
- packages/one-app-locale-bundler/package.json
- packages/one-app-runner/CHANGELOG.md
- packages/one-app-runner/package-lock.json
- packages/one-app-runner/package.json
- @americanexpress/eslint-plugin-one-app@6.10.0
- @americanexpress/generator-one-app-module@6.10.0
- @americanexpress/one-app-bundler@6.10.0
- @americanexpress/one-app-locale-bundler@6.3.0
- @americanexpress/one-app-runner@6.10.0
> chore(release): 6.10.0

- .github/ISSUE_TEMPLATE/bug-report.md
> chore(template): add npx envinfo command

- packages/generator-one-app-module/__tests__/app.js
- packages/generator-one-app-module/generators/app/index.js
- packages/generator-one-app-module/generators/app/templates/base-child-module/package.json
- packages/generator-one-app-module/generators/app/templates/root-module/__tests__/appConfig.spec.js
This takes care of some of the deps in @Francois-Esquire ticket #29
> feat(deps): update generated module deps

- packages/one-app-bundler/package-lock.json
- packages/one-app-bundler/package.json
- packages/one-app-bundler/webpack/module/webpack.client.js
This PR replaces #95 since the tests were failing
> chore(deps): bump read-pkg-up from 4.0.0 to 7.0.1

- packages/one-app-bundler/__tests__/webpack/loaders/__snapshots__/meta-data-loader.spec.js.snap
- packages/one-app-bundler/__tests__/webpack/loaders/__snapshots__/provided-externals-loader.spec.js.snap
- packages/one-app-bundler/__tests__/webpack/loaders/__snapshots__/validate-externals-loader.spec.js.snap
- packages/one-app-bundler/__tests__/webpack/loaders/__snapshots__/validate-one-app-compatibility-loader.spec.js.snap
- packages/one-app-bundler/__tests__/webpack/loaders/meta-data-loader.spec.js
- packages/one-app-bundler/__tests__/webpack/loaders/provided-externals-loader.spec.js
- packages/one-app-bundler/__tests__/webpack/loaders/validate-externals-loader.spec.js
- packages/one-app-bundler/__tests__/webpack/loaders/validate-one-app-compatibility-loader.spec.js
- packages/one-app-bundler/webpack/loaders/meta-data-loader.js
- packages/one-app-bundler/webpack/loaders/provided-externals-loader.js
- packages/one-app-bundler/webpack/loaders/validate-one-app-compatibility-loader.js
- packages/one-app-bundler/webpack/loaders/validate-required-externals-loader.js
Loaders were not properly throwing if index.js was not correctly formatted
> fix(errors): fix loaders not throwing correctly

- packages/generator-one-app-module/__tests__/app.js
- packages/generator-one-app-module/generators/app/index.js
- packages/generator-one-app-module/generators/app/templates/base-child-module/package.json
So I didn't update `babel-eslint` which is now a new library as we should do some testing around that first.
> chore(deps): update generator deps

- .github/workflows/release.yml
- .github/workflows/tests.yml
Updates the checkout action with correct configuration for commit linting
> fix(commitlint): validate commit message on ci

- packages/one-app-bundler/__tests__/.eslintrc.json
- packages/one-app-bundler/__tests__/webpack/__snapshots__/webpack.common.spec.js.snap
- packages/one-app-bundler/__tests__/webpack/app/__snapshots__/webpack.client.spec.js.snap
- packages/one-app-bundler/__tests__/webpack/module/webpack.client.spec.js
- packages/one-app-bundler/__tests__/webpack/webpack.common.spec.js
- packages/one-app-bundler/package.json
- packages/one-app-bundler/webpack/webpack.common.js
- yarn.lock
This reverts commit 3c93f645e0f601924381b4504dbec0625e222935.
> Revert "chore(eslint-plugin): switch to plugin instead of rule (#193)"

- .github/workflows/release.yml
Fixes indentation for invalid workflow file when releasing.
> chore(release): fix action indentation

- package.json
- yarn.lock
This is the replace the following two PRs:
https://github.com/americanexpress/one-app-cli/pull/231
https://github.com/americanexpress/one-app-cli/pull/233
> chore(deps): update commitlint libraries

- .github/pull_request_template.md
- packages/holocron-dev-server/__tests__/src/utils/config.spec.js
- packages/holocron-dev-server/__tests__/src/utils/statics.spec.js
- packages/holocron-dev-server/src/utils/config.js
- packages/holocron-dev-server/src/utils/statics.js
Merge Main to beta for a new release
> merge main to beta

- package.json
- yarn.lock
> chore(lerna): update v4

- .github/workflows/publish.yml
fixes issue with manual publish looking for a event branch that does not exist.
> fix(workflow): publish target main

- .github/workflows/publish.yml
> chore(publish): add PA token

- CONTRIBUTING.md
Add more clarity around release process.
> chore(contributing): update release process

- packages/holocron-dev-server/CHANGELOG.md
- packages/holocron-dev-server/package.json
- packages/one-app-bundler/CHANGELOG.md
- packages/one-app-bundler/package.json
- packages/one-app-locale-bundler/CHANGELOG.md
- packages/one-app-locale-bundler/package.json
- @americanexpress/holocron-dev-server@0.1.2
- @americanexpress/one-app-bundler@6.14.2
- @americanexpress/one-app-locale-bundler@6.5.2
DO NOT SQUASH AND MERGE
> chore(release): publish packages

- CONTRIBUTING.md
- package.json
removing the from-package option will enable lerna publish to also be responsible for creating tags and the changelog
> chore(workflow-publish): enable full publish

- .github/labeler.yml
always add one-app-review-requested label
> chore(labeler): always add one-app-review-requested

- package.json
- packages/one-app-bundler/package.json
- packages/one-app-bundler/webpack/webpack.common.js
- yarn.lock
Replace deprecated babel-eslint with @babel/eslint-parser
> feat(bundler-parser): @babel/eslint-parser

- .github/workflows/publish.yml
> chore(workflows): publish use token

- .github/workflows/labeler.yml
'These are the same approved changes from https://github.com/americanexpress/eslint-config-amex/pull/99 '
Updating git hub actions pertaining to labeling for one-app team
-> update to repo config
> chore(labeler): adding updated workflows

- packages/one-app-bundler/package.json
- yarn.lock
Updated holocron to fix backward compatibility isssue for one-app-bundler
Updated holocron to fix backward compatibility isssue for one-app-bundler
`holocronModule`  string is added as library name in one-app-bundler. 
The changes made to default string on holocron module name will cause reference error. 
- [ X] Bug fix (non-breaking change which fixes an issue)
> fix(update-holocron): updated holocron to 1.2.3

- packages/holocron-dev-server/CHANGELOG.md
- packages/holocron-dev-server/package.json
- packages/one-app-bundler/CHANGELOG.md
- packages/one-app-bundler/package.json
one-app-bundler 6.14.2 => 6.15.0
holocron-dev-server 0.1.2 => 0.1.3
one-app bundler
- fix lazy loading
- feat bundler-parser
holocron-dev-server
- fix path sep issue
Tested in production application and added test case. It was tested with` holocron v1.2.3`.
> chore(release): v0.1.3 and v6.15.0

- packages/holocron-dev-server/CHANGELOG.md
- packages/holocron-dev-server/package.json
- packages/one-app-bundler/CHANGELOG.md
- packages/one-app-bundler/package.json
Reverts americanexpress/one-app-cli#452
> chore(release): revert v0.1.3 and v6.15.0

- packages/holocron-dev-server/CHANGELOG.md
- packages/holocron-dev-server/package.json
- packages/one-app-bundler/CHANGELOG.md
- packages/one-app-bundler/package.json
one-app-bundler 6.14.2 => 6.15.0
holocron-dev-server 0.1.2 => 0.1.3
one-app bundler
- fix lazy loading
- feat bundler-parser
holocron-dev-server
- fix path sep issue
Tested in production application and added test case. It was tested with` holocron v1.2.3`.
> chore(release): v0.15.0 and v0.1.3

- package.json
> chore(lerna): publish with from-package

- .github/workflows/health-check.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml
- packages/generator-one-app-module/__tests__/app.js
- packages/generator-one-app-module/generators/app/index.js
- packages/generator-one-app-module/package.json
- packages/one-app-bundler/__tests__/webpack/webpack.common.spec.js
- packages/one-app-bundler/webpack/webpack.common.js
- yarn.lock
Reverts americanexpress/one-app-cli#465
This caused unexpected errors not seen when testing
> Revert "fix(bundler): default hashing method doesnt work in node 18"

- packages/eslint-plugin-one-app/package.json
- packages/generator-one-app-module/package.json
- packages/one-app-bundler/package.json
- packages/one-app-locale-bundler/package.json
- packages/one-app-runner/package.json
> chore(package): remove deadname

- packages/generator-one-app-module/README.md
- packages/generator-one-app-module/docs/Bundling-Modules.md
- packages/holocron-dev-server/README.md
- packages/one-app-runner/README.md
Documentation update for broken urls.
- Holocron modules url https://github.com/americanexpress/one-app/blob/main/docs/api/API.md#modules replaced with [url](https://github.com/americanexpress/one-app/tree/main/docs/api#modules)
- Mocking-Api-Calls url https://github.com/americanexpress/one-app/blob/main/docs/recipes/Mocking-API-Calls.md replaced with [url ](https://github.com/americanexpress/one-app/blob/main/docs/guides/Mocking-Api-Calls.md)
- Broken Internationalization url fixed in `packages/generator-one-app-module/docs/Bundling-Modules.md`
- Broken react-refresh-troubleshooting url fixed in `packages/holocron-dev-server/README.md`
Fixes issue - #472 
Certain One-App links within documentation are broken, preventing users from accessing the urls.
> docs(fix-links): one-app broken links fixed within documentation

- packages/one-app-runner/package.json
module not found for waitForOk.
module not found for waitForOk. utils folder was added to package.json
> fix(module): module not found waitForOk

- packages/one-app-dev-bundler/package.json
This change should instruct Lerna to publish this package publicly
Also change the version to 1.0.0 for the _first_ release
> chore(package): update publish config for public package

- README.md
- package.json
- packages/one-app-bundler/README.md
- packages/one-app-bundler/__tests__/bin/bundle-module.spec.js
- packages/one-app-bundler/__tests__/bin/webpack-bundle-module.spec.js
- packages/one-app-bundler/bin/bundle-module.js
- packages/one-app-bundler/bin/webpack-bundle-module.js
- packages/one-app-bundler/package.json
- packages/one-app-dev-bundler/README.md
- packages/one-app-dev-bundler/__tests__/esbuild/plugins/one-app-index-loader.spec.js
- packages/one-app-dev-bundler/esbuild/plugins/one-app-index-loader-injectors/app-compatibility-injector.js
- packages/one-app-dev-bundler/esbuild/plugins/one-app-index-loader-injectors/dev-live-reloader-injector.js
- packages/one-app-dev-bundler/esbuild/plugins/one-app-index-loader-injectors/holocron-module-register-injector.js
- packages/one-app-dev-bundler/esbuild/plugins/one-app-index-loader-injectors/module-metadata-injector.js
- packages/one-app-dev-bundler/esbuild/plugins/one-app-index-loader-injectors/provided-externals-injector.js
- yarn.lock
This allows the dev bundler to be involved through the prod bundler using the `--dev` flag
The relevant READMEs have been updated ready for this change.
This will allow users of one-app-bundler to perform a minor version upgrade to get access to the dev bundler.
Unit tests have been added, the package has been packed and installed and tested locally
> feat(bundler): enable dev bundler through flag

- packages/one-app-dev-bundler/__tests__/esbuild/__snapshots__/generateESBuildOptions.spec.js.snap
- packages/one-app-dev-bundler/esbuild/generateESBuildOptions.js
- packages/one-app-dev-bundler/package.json
- yarn.lock
Add node polyfill
Modules using node packages, like `stream`, will successfully build in our production bundler, but not the dev bundler.
> fix(devBundler): add node polyfill

- README.md
Updates spelling in the README.
While "alternal" may or may not be a real word, it's definitely not as common as "alternate".
>Alternal (adj)
>al-tur-nal
>
>Rare form of alternate
>
>Late 16th century; earliest use found in Thomas Newton (d. 1607), translator and Church of England clergyman. From post-classical Latin alternalis from classical Latin alternus + -ālis.
> docs(readme): correct spelling error

- packages/one-app-locale-bundler/__tests__/src/compileModuleLocales.spec.js
- packages/one-app-locale-bundler/package.json
resolve an eslint exception by listing a devDep
minimize eslint exceptions used!
eslint passes
> refactor(one-app-locale-bundler): add mock-fs as devDep

- packages/one-app-bundler/__tests__/utils/patchedCryptoHash.spec.js
- packages/one-app-bundler/utils/patchedCryptoHash.js
- packages/one-app-bundler/webpack/app/webpack.client.js
- packages/one-app-bundler/webpack/module/webpack.client.js
Node 18 ships with a new OpenSSL provider, which has dropped support for the old md4 cryptographic hashing algorithm that is used internally by Webpack 4. This PR has patched cryptoHash function to work with md4.
It fixes bug
`node:internal/crypto/hash:71
this[kHandle] = new _Hash(algorithm, xofLen);
^
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:133:10)`
Added test cases for change and taken below steps on module.
Steps:
1. Cloned internal module
2. Used node v18
3. Ran npm i (which throws crypto hash error due to webpack 4)
4. Used npm i ../local/one-app-bundler-with-patched-crypto-hash
5. Deleted node_modules
6. Ran npm i again successfully.
> fix(cyptoHash): patch crypto hash to support md4 hash

- .github/workflows/health-check.yml
- .github/workflows/tests.yml
- yarn.lock
add github action checks for node 18.x support 
node 16 is heading towards end of life and its time to support the LTS version
> chore(node18): add to unit testing

- packages/one-app-bundler/README.md
Corrects the invalid markdown in the readme by closing the first code block.
Updates the header levels to be properly nested.
Adds some new header sections so that items don't appear to be under the incorrect sections.
Fixes #544 
Verified rendering in GitHub editor.
> chore(readme): fix up purgecss section

- packages/one-app-bundler/README.md
this is an update to the readme documenting one-app-bundlers capability to accept typescript without further configuration
> docs(typescript): add documentation stating typescript is supported

- packages/one-app-bundler/package.json
- yarn.lock
fixing the webpack version to 4.46.0
> chore(dep): fix webpack version to 4.46.0

- packages/one-app-dev-bundler/__tests__/utils/bundle-external-fallbacks.spec.js
- packages/one-app-dev-bundler/utils/bundle-external-fallbacks.js
fix - handle when no one-amex key is in the `package.json`
bug fix
locally tested and added unit test.
> fix(externals): issue when no one-amex key

- .github/workflows/set-tag.yml
add new workflow to allow npm registry tagging. 
npm registry will always tag the last release as latest, this can lead to issues with releasing alpha versions.
> chore(workflow): add new set tag workflow

- packages/one-app-runner/__tests__/src/__snapshots__/startApp.spec.js.snap
- packages/one-app-runner/__tests__/src/startApp.spec.js
- packages/one-app-runner/src/startApp.js
Pass command arguments as arguments rather than allowing the shell to parse user input.
>If the shell option is enabled, do not pass unsanitized user input to this function. Any input containing shell metacharacters may be used to trigger arbitrary command execution
https://nodejs.org/docs/latest-v18.x/api/child_process.html#child_processspawncommand-args-options
I used `$ npm pack` etc to test with a module and unit tests should be the same though inspecting the `args` instead of `command` now and moved to inline snapshots instead of putting them in another file.
> fix(one-app-runner): avoid shell usage

- packages/one-app-dev-bundler/esbuild/plugins/styles-loader.js
- packages/one-app-dev-bundler/package.json
- yarn.lock
sass has made changes to the export api for ESM build going from default CJS export with no named exports to no default export and only named exports. This currently can result in errors being thrown during module builds depending on which version of sass was installed. 
Update to the latest sass version which uses named exports. Hopefully the api will now remain settled..
Below is a list of some relevant dart sass releases :
https://github.com/sass/dart-sass/releases/tag/1.63.6
https://github.com/sass/dart-sass/releases/tag/1.63.5
https://github.com/sass/dart-sass/releases/tag/1.63.4
https://github.com/sass/dart-sass/releases/tag/1.63.3
Modules using sass may not be able to build depending on which version of 'sass' they have installed.
This update uses ^1.68.0 which should result in …
> fix(one-app-dev-bundler): sass style loader

- CHANGELOG.md
Added updated CHANGELOG locations to root CHANGELOG file.
Address https://github.com/americanexpress/one-app-cli/issues/591
Address https://github.com/americanexpress/one-app-cli/issues/591
> chore(changelog): reference package changelogs

- packages/one-app-dev-bundler/esbuild/plugins/styles-loader.js
- packages/one-app-dev-bundler/esbuild/utils/load-styles.js
- packages/one-app-dev-bundler/esbuild/utils/server-style-aggregator.js
- packages/one-app-dev-bundler/index.js
Expose the scss loading system ready to be shared with the webpack bundler
Having as many parts of the two systems driven by the same code reduces the chance of issues when moving from the dev bundler to the prod bundler.
Green state change (no tests changed, no tests failed)
> feat(devBundler): expose css loading system for reuse

- packages/one-app-server-bundler/CHANGELOG.md
- packages/one-app-server-bundler/package.json
- @americanexpress/one-app-server-bundler@1.0.2
> Release @americanexpress/one-app-server-bundler@1.0.2

- packages/one-app-bundler/__tests__/utils/getConfigOptions.spec.js
- packages/one-app-bundler/__tests__/webpack/__snapshots__/webpack.common.spec.js.snap
- packages/one-app-bundler/__tests__/webpack/plugins/restrict-runtime-symbols.spec.js
- packages/one-app-bundler/__tests__/webpack/webpack.common.spec.js
- packages/one-app-bundler/webpack/plugins/restrict-runtime-symbols.js
- packages/one-app-bundler/webpack/webpack.common.js
- packages/one-app-dev-bundler/esbuild/plugins/restrict-runtime-symbols.js
- packages/one-app-dev-bundler/index.js
- yarn.lock
This validation was lost in the upgrade to webpack 5, restore it
> fix(appConfig): restore check to app config

- README.md
Added notice of innersourcing to README
Prep for archival
N/A
> docs(readme): innersource notice
